SHOT_LENGTH = 3  # Number of consecutive shots to consider
SURFACES = ["hard", "clay", "grass"]
MIN_NUM_OF_POINTS = 30  # Minimum number of points per player per context to be included in clustering
MIN_SUPPORT = 0.01  # Minimum support for frequent sequences
MIN_SEQUENCE_LENGTH = 3  # Minimum sequence length
TOP_PATTERNS = 50  # Number of frequent patterns to include in the dictionary
MIN_PLAYERS = 3  # Minimum number of players using a pattern for it to be considered among the top patterns

PLAYERS = ['Abedallah_Shelbayh', 'Adam_Walton', 'Adrian_Andreev', 'Adrian_Mannarino', 'Albert_Ramos',
           'Alejandro_Davidovich_Fokina', 'Alejandro_Moro_Canas', 'Alejandro_Tabilo', 'Aleksandar_Kovacevic',
           'Aleksandar_Vukic', 'Aleksandre_Metreveli', 'Alessandro_Giannessi', 'Alex_Barrena', 'Alex_Bolt',
           'Alex_De_Minaur', 'Alex_Marti_Pujolras', 'Alex_Michelsen', 'Alex_Molcan', 'Alexander_Blockx',
           'Alexander_Bublik', 'Alexander_Cozbinov', 'Alexander_Ritschard', 'Alexander_Shevchenko', 'Alexander_Zverev',
           'Alexandre_Muller', 'Alexei_Popyrin', 'Alexis_Galarneau', 'Alvaro_Guillen_Meza', 'Andrea_Pellegrino',
           'Andrea_Vavassori', 'Andreas_Seppi', 'Andrej_Martin', 'Andrey_Rublev', 'Andy_Murray', 'Antoine_Bellier',
           'Antoine_Escoffier', 'Aristotelis_Thanos', 'Arklon_Huertas_Del_Pino', 'Arthur_Cazaux', 'Arthur_Fery',
           'Arthur_Fils', 'Arthur_Rinderknech', 'Aslan_Karatsev', 'Attila_Balazs', 'Ben_Shelton', 'Benjamin_Bonzi',
           'Benjamin_Hassan', 'Benoit_Paire', 'Bernabe_Zapata_Miralles', 'Bernard_Tomic', 'Billy_Harris', 'Borna_Coric',
           'Borna_Gojo', 'Botic_Van_De_Zandschulp', 'Brandon_Holt', 'Brandon_Nakashima', 'Brian_Battistone',
           'Bruno_Kuzuhara', 'Bu_Yunchaokete', 'Cameron_Norrie', 'Camilo_Ugo_Carabelli', 'Carlos_Alcaraz',
           'Carlos_Gimeno_Valero', 'Carlos_Taberner', 'Casper_Ruud', 'Cem_Ilkel', 'Charles_Broom', 'Christian_Harrison',
           'Christoph_Negritu', 'Christopher_Eubanks', 'Christopher_Oconnell', 'Chun_Hsin_Tseng', 'Coleman_Wong',
           'Colton_Smith', 'Conner_Huertas_Del_Pino', 'Constant_Lestienne', 'Cooper_Kose', 'Cooper_Williams',
           'Corentin_Moutet', 'Cristian_Garin', 'Dalibor_Svrcina', 'Damir_Dzumhur', 'Daniel_Altmaier',
           'Daniel_Dutra_Da_Silva', 'Daniel_Elahi_Galan', 'Daniel_Evans', 'Daniel_Masur', 'Daniel_Michalski',
           'Daniel_Rincon', 'Daniil_Medvedev','David_Goffin', 'Denis_Istomin', 'Denis_Kudla', 'Denis_Shapovalov',
           'Dennis_Novak', 'Diego_Schwartzman', 'Dimitar_Kuzmanov', 'Dino_Prizmic', 'Dmitry_Popko', 'Dominic_Stricker',
           'Dominic_Thiem', 'Dominik_Koepfer', 'Duje_Ajdukovic', 'Dusan_Lajovic', 'Dylan_Dietrich', 'Egor_Gerasimov'
           'Elias_Ymer', 'Elliot_Benchetrit', 'Emil_Ruusuvuori', 'Emilio_Gomez', 'Emilio_Nava', 'Enzo_Couacaud',
           'Ernests_Gulbis', 'Ethan_Quinn', 'Evan_Furness', 'Evan_Zhu', 'Evgeny_Donskoy', 'Fabian_Marozsan',
           'Fabio_Fognini', 'Facundo_Bagnis', 'Facundo_Diaz_Acosta', 'Facundo_Mena', 'Federico_Agustin_Gomez',
           'Federico_Cina', 'Federico_Coria', 'Federico_Delbonis', 'Federico_Gaio', 'Feliciano_Lopez',
           'Felix_Auger_Aliassime', 'Fernando_Verdasco', 'Filip_Bergevi', 'Filip_Cristian_Jianu', 'Filip_Horansky',
           'Filip_Krajinovic', 'Filip_Misolic', 'Fitriadi_M_Rifqi', 'Flavio_Cobolli', 'Frances_Tiafoe',
           'Francesco_Maestrelli', 'Francesco_Passaro', 'Francisco_Cerundolo', 'Francisco_Comesana', 'Francisco_Llanes',
           'Gabriel_Decamps', 'Gabriel_Diallo', 'Gael_Monfils', 'Genaro_Alberto_Olivieri', 'Gijs_Brouwer',
           'Gilles_Arnaud_Bailly', 'Gilles_Simon', 'Giovanni_Mpetshi_Perricard', 'Giulio_Zeppieri', 'Goncalo_Oliveira',
           'Gregoire_Barrere', 'Grigor_Dimitrov', 'Guido_Pella', 'Guy_Den_Ouden', 'Hamad_Medjedovic', 'Harold_Mayot',
           'Henri_Laaksonen', 'Henrique_Rocha', 'Hernan_Casanova', 'Holger_Rune', 'Hubert_Hurkacz', 'Hugo_Dellien',
           'Hugo_Gaston', 'Hugo_Grenier', 'Illya_Marchenko', 'Ilya_Ivashka', 'Inaki_Montes_De_La_Torre', 'Ivo_Karlovic',
           'J_J_Wolf', 'Jack_Draper', 'Jack_Sock', 'Jacob_Fearnley', 'Jakub_Mensik', 'James_Duckworth', 'James_Mccabe',
           'James_Trotter', 'Jan_Choinski', 'Jan_Kumstat', 'Jan_Lennard_Struff', 'Jannik_Sinner', 'Jason_Jung',
           'Jason_Kubler', 'Jaume_Munar', 'Javier_Barranco_Cosano', 'Jelle_Sels', 'Jenson_Brooksby', 'Jeremy_Chardy',
           'Jerome_Kym', 'Jerzy_Janowicz', 'Jesper_De_Jong', 'Jiri_Lehecka', 'Jiri_Vesely', 'Jo_Wilfried_Tsonga',
           'Joao_Fonseca', 'Joao_Menezes', 'Joao_Sousa', 'John_Isner', 'John_Millman', 'Jordan_Thompson',
           'Joris_De_Loore', 'Joshua_Sheehy', 'Jozef_Kovalik', 'Juan_Carlos_Prado_Angelo', 'Juan_Ignacio_Londero',
           'Juan_Manuel_Cerundolo', 'Juan_Martin_Del_Potro', 'Juan_Pablo_Ficovich', 'Juan_Pablo_Varillas',
           'Juncheng_Shang', 'Jurij_Rodionov', 'Karen_Khachanov', 'Karim_Mohamed_Maamoun', 'Karlis_Ozolins',
           'Karue_Sell', 'Kaylan_Bigun', 'Kei_Nishikori', 'Kevin_Anderson', 'Kilian_Feldbausch', 'Kimmer_Coppejans',
           'Kiranpal_Pannu', 'Kris_Van_Wyk', 'Kyle_Edmund', 'Kyrian_Jacquet', 'Laslo_Djere', 'Laurent_Lokoli',
           'Leandro_Riedi', 'Learner_Tien', 'Leo_Borg', 'Li_Tu', 'Liam_Broady', 'Liam_Draxl', 'Lloyd_Harris',
           'Lorenzo_Musetti', 'Lorenzo_Sonego', 'Luca_Nardi', 'Luca_Van_Assche', 'Lucas_Catarina', 'Lucas_Pouille',
           'Luciano_Darderi', 'Lukas_Klein', 'Lukas_Lacko', 'Lukas_Neumayer', 'Mackenzie_Mcdonald', 'Maks_Kasnikowski',
           'Malek_Jaziri', 'Marc_Andrea_Huesler', 'Marc_Polmans', 'Marco_Cecchinato', 'Marco_Trungelliti',
           'Marcos_Giron', 'Mariano_Navone', 'Marin_Cilic', 'Mark_Lajal', 'Martin_Borisiouk', 'Martin_Cuevas',
           'Martin_Landaluce', 'Marton_Fucsovics', 'Masamichi_Imamura', 'Mateus_Alves', 'Matteo_Arnaldi',
           'Matteo_Berrettini', 'Matteo_Martineau', 'Matthew_Ebden', 'Mattia_Bellucci', 'Matwe_Middelkoop',
           'Max_Hans_Rehberg', 'Max_Houkes', 'Max_Purcell', 'Maxime_Cressy', 'Maximilian_Marterer',
           'Maximilian_Neuchrist', 'Michael_Geerts', 'Michael_Mmoh', 'Michael_Zheng', 'Mikael_Ymer',
           'Mikhail_Kukushkin', 'Mili_Poljicak', 'Miljan_Zekic', 'Milos_Raonic', 'Minhtuan_Pham', 'Miomir_Kecmanovic',
           'Mischa_Zverev', 'Moez_Echargui', 'Mohamed_Safwat', 'Naoki_Nakagawa', 'Nick_Hardt', 'Nick_Kyrgios',
           'Nicola_Kuhn', 'Nicolai_Budkov_Kjaer', 'Nicolas_Alvarez_Varona', 'Nicolas_Jarry', 'Nicolas_Mahut',
           'Nicolas_Mejia', 'Niels_Visker', 'Nikoloz_Basilashvili', 'Nino_Serdarusic', 'Nishesh_Basavareddy',
           'Norbert_Gombos', 'Novak_Djokovic', 'Nuno_Borges', 'Oleksandr_Ovcharenko', 'Oleksii_Krutykh', 'Omar_Jasika',
           'Oscar_Otte', 'Otto_Virtanen', 'Ozan_Baris', 'Pablo_Andujar', 'Pablo_Carreno_Busta', 'Pablo_Cuevas',
           'Pablo_Llamas_Ruiz', 'Patrick_Brady', 'Patrick_Kaukovalta', 'Patrick_Kypson', 'Paul_Jubb', 'Pavel_Kotov',
           'Pedro_Araujo', 'Pedro_Cachin', 'Pedro_Martinez', 'Peter_Bertran', 'Peter_Fajta', 'Peter_Gojowczyk',
           'Petros_Tsitsipas', 'Pierre_Hugues_Herbert', 'Pol_Martin_Tiffon', 'Prajnesh_Gunneswaran', 'Quentin_Halys',
           'Radu_Albot', 'Rafael_Nadal', 'Raphael_Collignon', 'Raul_Brancaccio', 'Rei_Sakamoto', 'Reilly_Opelka',
           'Renzo_Olivo', 'Ricardas_Berankis', 'Richard_Gasquet', 'Rinky_Hijikata', 'Rio_Noguchi',
           'Roberto_Bautista_Agut', 'Roberto_Carballes_Baena', 'Roberto_Marcora', 'Roberto_Quiroz', 'Robin_Haase',
           'Roger_Federer', 'Roman_Andres_Burruchaga', 'Roman_Safiullin', 'Ryan_Seggerman', 'Salvatore_Caruso',
           'Sam_Querrey', 'Sascha_Gueymard_Wayenburg', 'Sebastian_Baez', 'Sebastian_Korda', 'Sebastian_Ofner',
           'Seong_Chan_Hong', 'Sergey_Fomin', 'Sergiy_Stakhovsky', 'Shintaro_Mochizuki', 'Sho_Shimabukuro',
           'Soon_Woo_Kwon', 'Stan_Wawrinka', 'Stefan_Kozlov', 'Stefanos_Tsitsipas', 'Steve_Darcis', 'Steve_Johnson',
           'Steven_Diez', 'Strong_Kirchheimer', 'Sumit_Nagal', 'Tallon_Griekspoor', 'Taro_Daniel', 'Taylor_Fritz',
           'Tennys_Sandgren', 'Thanasi_Kokkinakis', 'Thiago_Agustin_Tirante', 'Thiago_Monteiro', 'Thiago_Seyboth_Wild',
           'Thijs_Boogaard', 'Thomaz_Bellucci', 'Tim_Van_Rijthoven', 'Timofey_Skatov', 'Titouan_Droguet',
           'Tomas_Barrios_Vera', 'Tomas_Machac', 'Tomas_Martin_Etcheverry', 'Tomasz_Berkieta', 'Tommy_Paul',
           'Tommy_Robredo', 'Tristan_Schoolkate', 'Tung_Lin_Wu', 'Ugo_Blanchet', 'Ugo_Humbert', 'Valentin_Vacherot',
           'Vasek_Pospisil', 'Viktor_Durasovic', 'Viktor_Troicki', 'Vilius_Gaubas', 'Vit_Kopriva', 'Yannick_Hanfmann',
           'Yasutaka_Uchiyama', 'Yibing_Wu', 'Yoshihito_Nishioka', 'Yosuke_Watanuki', 'Younes_Lalami_Laaroussi',
           'Yu_Hsiou_Hsu', 'Yuichi_Sugita', 'Zachary_Svajda', 'Zdenek_Kolar', 'Zhizhen_Zhang', 'Zizou_Bergs',
           'Zsombor_Piros']

PLAYER_SURFACES_DICT = {'Abedallah_Shelbayh': {'hard'}, 'Adam_Walton': {'hard'}, 'Adrian_Andreev': {'hard', 'clay'},
                        'Adrian_Mannarino': {'grass', 'hard'}, 'Albert_Ramos': {'grass', 'hard', 'clay'},
                        'Alejandro_Davidovich_Fokina': {'grass', 'hard', 'clay'},
                        'Alejandro_Moro_Canas': {'grass', 'clay'},
                        'Alejandro_Tabilo': {'grass', 'hard', 'clay'}, 'Aleksandar_Kovacevic': {'hard'},
                        'Aleksandar_Vukic': {'hard', 'clay'},
                        'Aleksandre_Metreveli': {'hard'}, 'Alessandro_Giannessi': {'hard'}, 'Alex_Barrena': {'clay'},
                        'Alex_Bolt': {'hard'},
                        'Alex_De_Minaur': {'grass', 'hard', 'clay'}, 'Alex_Marti_Pujolras': {'clay'},
                        'Alex_Michelsen': {'grass', 'hard'},
                        'Alex_Molcan': {'hard', 'clay'}, 'Alexander_Blockx': {'hard'},
                        'Alexander_Bublik': {'grass', 'hard', 'clay'},
                        'Alexander_Cozbinov': {'hard'}, 'Alexander_Ritschard': {'clay'},
                        'Alexander_Shevchenko': {'grass', 'hard', 'clay'},
                        'Alexander_Zverev': {'grass', 'hard', 'clay'}, 'Alexandre_Muller': {'grass', 'hard', 'clay'},
                        'Alexei_Popyrin': {'grass', 'hard', 'clay'}, 'Alexis_Galarneau': {'hard', 'clay'},
                        'Alvaro_Guillen_Meza': {'hard'},
                        'Andrea_Pellegrino': {'clay'}, 'Andrea_Vavassori': {'hard', 'clay'}, 'Andreas_Seppi': {'hard'},
                        'Andrej_Martin': {'hard', 'clay'}, 'Andrey_Rublev': {'grass', 'hard', 'clay'},
                        'Andy_Murray': {'grass', 'hard', 'clay'}, 'Antoine_Bellier': {'grass'},
                        'Antoine_Escoffier': {'hard'},
                        'Aristotelis_Thanos': {'hard'}, 'Arklon_Huertas_Del_Pino': {'clay'},
                        'Arthur_Cazaux': {'hard', 'clay'},
                        'Arthur_Fery': {'grass'}, 'Arthur_Fils': {'grass', 'hard', 'clay'},
                        'Arthur_Rinderknech': {'grass', 'hard', 'clay'},
                        'Aslan_Karatsev': {'grass', 'hard', 'clay'}, 'Attila_Balazs': {'hard'},
                        'Ben_Shelton': {'grass', 'hard', 'clay'},
                        'Benjamin_Bonzi': {'hard', 'clay'}, 'Benjamin_Hassan': {'clay'},
                        'Benoit_Paire': {'grass', 'hard', 'clay'},
                        'Bernabe_Zapata_Miralles': {'hard', 'clay'}, 'Bernard_Tomic': {'clay'},
                        'Billy_Harris': {'hard', 'clay'},
                        'Borna_Coric': {'grass', 'hard', 'clay'}, 'Borna_Gojo': {'hard'},
                        'Botic_Van_De_Zandschulp': {'grass', 'hard', 'clay'},
                        'Brandon_Holt': {'hard'}, 'Brandon_Nakashima': {'grass', 'hard', 'clay'},
                        'Brian_Battistone': {'hard'},
                        'Bruno_Kuzuhara': {'hard'}, 'Bu_Yunchaokete': {'hard'},
                        'Cameron_Norrie': {'grass', 'hard', 'clay'},
                        'Camilo_Ugo_Carabelli': {'hard', 'clay'}, 'Carlos_Alcaraz': {'grass', 'hard', 'clay'},
                        'Carlos_Gimeno_Valero': {'clay'}, 'Carlos_Taberner': {'hard'},
                        'Casper_Ruud': {'grass', 'hard', 'clay'},
                        'Cem_Ilkel': {'hard'}, 'Charles_Broom': {'grass'}, 'Christian_Harrison': {'hard'},
                        'Christoph_Negritu': {'hard'},
                        'Christopher_Eubanks': {'grass', 'hard', 'clay'},
                        'Christopher_Oconnell': {'grass', 'hard', 'clay'},
                        'Chun_Hsin_Tseng': {'hard', 'clay'}, 'Coleman_Wong': {'hard'}, 'Colton_Smith': {'hard'},
                        'Conner_Huertas_Del_Pino': {'clay'}, 'Constant_Lestienne': {'grass', 'hard'},
                        'Cooper_Kose': {'hard'},
                        'Cooper_Williams': {'hard'}, 'Corentin_Moutet': {'grass', 'hard', 'clay'},
                        'Cristian_Garin': {'grass', 'hard', 'clay'},
                        'Dalibor_Svrcina': {'hard', 'clay'}, 'Damir_Dzumhur': {'hard'},
                        'Daniel_Altmaier': {'grass', 'hard', 'clay'},
                        'Daniel_Dutra_Da_Silva': {'clay'}, 'Daniel_Elahi_Galan': {'grass', 'hard', 'clay'},
                        'Daniel_Evans': {'grass', 'hard', 'clay'}, 'Daniel_Masur': {'grass'},
                        'Daniel_Michalski': {'clay'},
                        'Daniel_Rincon': {'clay'}, 'Daniil_Medvedev': {'grass', 'hard', 'clay'},
                        'David_Goffin': {'grass', 'hard', 'clay'},
                        'Denis_Istomin': {'hard', 'clay'}, 'Denis_Kudla': {'hard'},
                        'Denis_Shapovalov': {'grass', 'hard', 'clay'},
                        'Dennis_Novak': {'grass', 'hard'}, 'Diego_Schwartzman': {'grass', 'hard', 'clay'},
                        'Dimitar_Kuzmanov': {'hard', 'clay'}, 'Dino_Prizmic': {'hard'},
                        'Dmitry_Popko': {'hard', 'clay'},
                        'Dominic_Stricker': {'grass', 'hard'}, 'Dominic_Thiem': {'grass', 'hard', 'clay'},
                        'Dominik_Koepfer': {'grass', 'hard', 'clay'}, 'Duje_Ajdukovic': {'hard'},
                        'Dusan_Lajovic': {'hard', 'clay'},
                        'Dylan_Dietrich': {'hard'}, 'Egor_Gerasimov': {'hard', 'clay'}, 'Elias_Ymer': {'hard', 'clay'},
                        'Elliot_Benchetrit': {'hard', 'clay'}, 'Emil_Ruusuvuori': {'grass', 'hard', 'clay'},
                        'Emilio_Gomez': {'hard'},
                        'Emilio_Nava': {'hard', 'clay'}, 'Enzo_Couacaud': {'hard'}, 'Ernests_Gulbis': {'hard'},
                        'Ethan_Quinn': {'hard'},
                        'Evan_Furness': {'hard'}, 'Evan_Zhu': {'hard'}, 'Evgeny_Donskoy': {'hard'},
                        'Fabian_Marozsan': {'hard', 'clay'},
                        'Fabio_Fognini': {'hard', 'clay'}, 'Facundo_Bagnis': {'hard', 'clay'},
                        'Facundo_Diaz_Acosta': {'hard', 'clay'},
                        'Facundo_Mena': {'clay'}, 'Federico_Agustin_Gomez': {'clay'}, 'Federico_Cina': {'hard'},
                        'Federico_Coria': {'hard', 'clay'}, 'Federico_Delbonis': {'grass', 'hard', 'clay'},
                        'Federico_Gaio': {'hard'},
                        'Feliciano_Lopez': {'grass', 'hard', 'clay'},
                        'Felix_Auger_Aliassime': {'grass', 'hard', 'clay'},
                        'Fernando_Verdasco': {'hard'}, 'Filip_Bergevi': {'hard'}, 'Filip_Cristian_Jianu': {'clay'},
                        'Filip_Horansky': {'clay'},
                        'Filip_Krajinovic': {'grass', 'hard', 'clay'}, 'Filip_Misolic': {'clay'},
                        'Fitriadi_M_Rifqi': {'hard'},
                        'Flavio_Cobolli': {'grass', 'hard', 'clay'}, 'Frances_Tiafoe': {'grass', 'hard', 'clay'},
                        'Francesco_Maestrelli': {'clay'}, 'Francesco_Passaro': {'clay'},
                        'Francisco_Cerundolo': {'grass', 'hard', 'clay'},
                        'Francisco_Comesana': {'grass', 'clay'}, 'Francisco_Llanes': {'hard'},
                        'Gabriel_Decamps': {'hard'},
                        'Gabriel_Diallo': {'hard', 'clay'}, 'Gael_Monfils': {'grass', 'hard', 'clay'},
                        'Genaro_Alberto_Olivieri': {'clay'},
                        'Gijs_Brouwer': {'hard', 'clay'}, 'Gilles_Arnaud_Bailly': {'hard'},
                        'Gilles_Simon': {'grass', 'hard', 'clay'},
                        'Giovanni_Mpetshi_Perricard': {'grass', 'hard'}, 'Giulio_Zeppieri': {'hard', 'clay'},
                        'Goncalo_Oliveira': {'hard', 'clay'}, 'Gregoire_Barrere': {'grass', 'hard', 'clay'},
                        'Grigor_Dimitrov': {'grass', 'hard', 'clay'}, 'Guido_Pella': {'hard'},
                        'Guy_Den_Ouden': {'clay'},
                        'Hamad_Medjedovic': {'grass', 'clay'}, 'Harold_Mayot': {'hard'}, 'Henri_Laaksonen': {'hard'},
                        'Henrique_Rocha': {'clay'}, 'Hernan_Casanova': {'clay'},
                        'Holger_Rune': {'grass', 'hard', 'clay'},
                        'Hubert_Hurkacz': {'grass', 'hard', 'clay'}, 'Hugo_Dellien': {'hard', 'clay'},
                        'Hugo_Gaston': {'grass', 'hard', 'clay'}, 'Hugo_Grenier': {'hard'}, 'Illya_Marchenko': {'clay'},
                        'Ilya_Ivashka': {'hard'}, 'Inaki_Montes_De_La_Torre': {'clay'}, 'Ivo_Karlovic': {'hard'},
                        'J_J_Wolf': {'hard', 'clay'},
                        'Jack_Draper': {'grass', 'hard', 'clay'}, 'Jack_Sock': {'hard', 'clay'},
                        'Jacob_Fearnley': {'grass'},
                        'Jakub_Mensik': {'hard', 'clay'}, 'James_Duckworth': {'grass', 'hard'},
                        'James_Mccabe': {'hard'},
                        'James_Trotter': {'hard'}, 'Jan_Choinski': {'grass', 'clay'}, 'Jan_Kumstat': {'hard'},
                        'Jan_Lennard_Struff': {'grass', 'hard', 'clay'}, 'Jannik_Sinner': {'grass', 'hard', 'clay'},
                        'Jason_Jung': {'clay'},
                        'Jason_Kubler': {'hard', 'clay'}, 'Jaume_Munar': {'hard', 'clay'},
                        'Javier_Barranco_Cosano': {'clay'},
                        'Jelle_Sels': {'hard', 'clay'}, 'Jenson_Brooksby': {'grass', 'hard', 'clay'},
                        'Jeremy_Chardy': {'grass', 'hard'},
                        'Jerome_Kym': {'hard'}, 'Jerzy_Janowicz': {'hard'}, 'Jesper_De_Jong': {'hard', 'clay'},
                        'Jiri_Lehecka': {'grass', 'hard', 'clay'}, 'Jiri_Vesely': {'grass', 'hard'},
                        'Jo_Wilfried_Tsonga': {'hard', 'clay'},
                        'Joao_Fonseca': {'hard', 'clay'}, 'Joao_Menezes': {'hard'}, 'Joao_Sousa': {'hard', 'clay'},
                        'John_Isner': {'grass', 'hard', 'clay'}, 'John_Millman': {'hard', 'clay'},
                        'Jordan_Thompson': {'grass', 'hard', 'clay'}, 'Joris_De_Loore': {'clay'},
                        'Joshua_Sheehy': {'hard'},
                        'Jozef_Kovalik': {'hard', 'clay'}, 'Juan_Carlos_Prado_Angelo': {'hard', 'clay'},
                        'Juan_Ignacio_Londero': {'clay'},
                        'Juan_Manuel_Cerundolo': {'grass', 'hard', 'clay'}, 'Juan_Martin_Del_Potro': {'clay'},
                        'Juan_Pablo_Ficovich': {'clay'},
                        'Juan_Pablo_Varillas': {'hard', 'clay'}, 'Juncheng_Shang': {'hard', 'clay'},
                        'Jurij_Rodionov': {'hard', 'clay'},
                        'Karen_Khachanov': {'hard', 'clay'}, 'Karim_Mohamed_Maamoun': {'hard'},
                        'Karlis_Ozolins': {'hard'},
                        'Karue_Sell': {'hard', 'clay'}, 'Kaylan_Bigun': {'clay'}, 'Kei_Nishikori': {'grass', 'hard'},
                        'Kevin_Anderson': {'hard'}, 'Kilian_Feldbausch': {'hard'}, 'Kimmer_Coppejans': {'clay'},
                        'Kiranpal_Pannu': {'hard'},
                        'Kris_Van_Wyk': {'hard'}, 'Kyle_Edmund': {'hard'}, 'Kyrian_Jacquet': {'hard'},
                        'Laslo_Djere': {'grass', 'hard', 'clay'}, 'Laurent_Lokoli': {'grass', 'hard'},
                        'Leandro_Riedi': {'hard'},
                        'Learner_Tien': {'hard'}, 'Leo_Borg': {'hard', 'clay'}, 'Li_Tu': {'hard'},
                        'Liam_Broady': {'grass', 'hard'},
                        'Liam_Draxl': {'hard'}, 'Lloyd_Harris': {'grass', 'hard'},
                        'Lorenzo_Musetti': {'grass', 'hard', 'clay'},
                        'Lorenzo_Sonego': {'grass', 'hard', 'clay'}, 'Luca_Nardi': {'hard', 'clay'},
                        'Luca_Van_Assche': {'hard', 'clay'},
                        'Lucas_Catarina': {'clay'}, 'Lucas_Pouille': {'hard', 'clay'},
                        'Luciano_Darderi': {'hard', 'clay'},
                        'Lukas_Klein': {'hard', 'clay'}, 'Lukas_Lacko': {'grass'}, 'Lukas_Neumayer': {'clay'},
                        'Mackenzie_Mcdonald': {'grass', 'hard'}, 'Maks_Kasnikowski': {'hard'},
                        'Malek_Jaziri': {'hard', 'clay'},
                        'Marc_Andrea_Huesler': {'grass', 'hard'}, 'Marc_Polmans': {'hard'},
                        'Marco_Cecchinato': {'hard', 'clay'},
                        'Marco_Trungelliti': {'clay'}, 'Marcos_Giron': {'grass', 'hard', 'clay'},
                        'Mariano_Navone': {'grass', 'hard', 'clay'},
                        'Marin_Cilic': {'grass', 'hard', 'clay'}, 'Mark_Lajal': {'grass'}, 'Martin_Borisiouk': {'hard'},
                        'Martin_Cuevas': {'hard'}, 'Martin_Landaluce': {'hard', 'clay'},
                        'Marton_Fucsovics': {'grass', 'hard', 'clay'},
                        'Masamichi_Imamura': {'hard'}, 'Mateus_Alves': {'clay'}, 'Matteo_Arnaldi': {'hard', 'clay'},
                        'Matteo_Berrettini': {'grass', 'hard', 'clay'}, 'Matteo_Martineau': {'clay'},
                        'Matthew_Ebden': {'hard'},
                        'Mattia_Bellucci': {'hard'}, 'Matwe_Middelkoop': {'hard'},
                        'Max_Hans_Rehberg': {'grass', 'clay'},
                        'Max_Houkes': {'clay'}, 'Max_Purcell': {'grass', 'hard'},
                        'Maxime_Cressy': {'grass', 'hard', 'clay'},
                        'Maximilian_Marterer': {'grass', 'clay'}, 'Maximilian_Neuchrist': {'clay'},
                        'Michael_Geerts': {'hard'},
                        'Michael_Mmoh': {'hard'}, 'Michael_Zheng': {'grass'}, 'Mikael_Ymer': {'hard', 'clay'},
                        'Mikhail_Kukushkin': {'hard'},
                        'Mili_Poljicak': {'grass', 'clay'}, 'Miljan_Zekic': {'clay'}, 'Milos_Raonic': {'grass', 'hard'},
                        'Minhtuan_Pham': {'hard'}, 'Miomir_Kecmanovic': {'grass', 'hard', 'clay'},
                        'Mischa_Zverev': {'hard'},
                        'Moez_Echargui': {'hard'}, 'Mohamed_Safwat': {'hard'}, 'Naoki_Nakagawa': {'hard'},
                        'Nick_Hardt': {'clay'},
                        'Nick_Kyrgios': {'grass', 'hard', 'clay'}, 'Nicola_Kuhn': {'grass', 'hard'},
                        'Nicolai_Budkov_Kjaer': {'clay'},
                        'Nicolas_Alvarez_Varona': {'clay'}, 'Nicolas_Jarry': {'grass', 'hard', 'clay'},
                        'Nicolas_Mahut': {'hard'},
                        'Nicolas_Mejia': {'hard', 'clay'}, 'Niels_Visker': {'hard'},
                        'Nikoloz_Basilashvili': {'grass', 'hard', 'clay'},
                        'Nino_Serdarusic': {'hard'}, 'Nishesh_Basavareddy': {'hard'}, 'Norbert_Gombos': {'hard'},
                        'Novak_Djokovic': {'grass', 'hard', 'clay'}, 'Nuno_Borges': {'hard', 'clay'},
                        'Oleksandr_Ovcharenko': {'clay'},
                        'Oleksii_Krutykh': {'hard', 'clay'}, 'Omar_Jasika': {'hard'},
                        'Oscar_Otte': {'grass', 'hard', 'clay'},
                        'Otto_Virtanen': {'grass', 'hard', 'clay'}, 'Ozan_Baris': {'hard'},
                        'Pablo_Andujar': {'hard', 'clay'},
                        'Pablo_Carreno_Busta': {'grass', 'hard', 'clay'}, 'Pablo_Cuevas': {'clay'},
                        'Pablo_Llamas_Ruiz': {'clay'},
                        'Patrick_Brady': {'hard'}, 'Patrick_Kaukovalta': {'hard'}, 'Patrick_Kypson': {'hard'},
                        'Paul_Jubb': {'grass', 'hard', 'clay'}, 'Pavel_Kotov': {'hard', 'clay'},
                        'Pedro_Araujo': {'clay'},
                        'Pedro_Cachin': {'hard', 'clay'}, 'Pedro_Martinez': {'grass', 'hard', 'clay'},
                        'Peter_Bertran': {'clay'},
                        'Peter_Fajta': {'clay'}, 'Peter_Gojowczyk': {'grass', 'hard'}, 'Petros_Tsitsipas': {'hard'},
                        'Pierre_Hugues_Herbert': {'hard', 'clay'}, 'Pol_Martin_Tiffon': {'clay'},
                        'Prajnesh_Gunneswaran': {'grass', 'hard', 'clay'}, 'Quentin_Halys': {'grass', 'hard', 'clay'},
                        'Radu_Albot': {'grass', 'hard', 'clay'}, 'Rafael_Nadal': {'grass', 'hard', 'clay'},
                        'Raphael_Collignon': {'hard', 'clay'}, 'Raul_Brancaccio': {'clay'}, 'Rei_Sakamoto': {'hard'},
                        'Reilly_Opelka': {'grass', 'hard', 'clay'}, 'Renzo_Olivo': {'clay'},
                        'Ricardas_Berankis': {'grass', 'hard'},
                        'Richard_Gasquet': {'grass', 'hard', 'clay'}, 'Rinky_Hijikata': {'grass', 'hard'},
                        'Rio_Noguchi': {'hard'},
                        'Roberto_Bautista_Agut': {'grass', 'hard', 'clay'}, 'Roberto_Carballes_Baena': {'hard', 'clay'},
                        'Roberto_Marcora': {'hard'}, 'Roberto_Quiroz': {'hard'}, 'Robin_Haase': {'hard', 'clay'},
                        'Roger_Federer': {'grass', 'hard', 'clay'}, 'Roman_Andres_Burruchaga': {'clay'},
                        'Roman_Safiullin': {'grass', 'hard', 'clay'}, 'Ryan_Seggerman': {'hard'},
                        'Salvatore_Caruso': {'clay'},
                        'Sam_Querrey': {'grass', 'hard'}, 'Sascha_Gueymard_Wayenburg': {'clay'},
                        'Sebastian_Baez': {'grass', 'hard', 'clay'},
                        'Sebastian_Korda': {'grass', 'hard', 'clay'}, 'Sebastian_Ofner': {'hard', 'clay'},
                        'Seong_Chan_Hong': {'hard'},
                        'Sergey_Fomin': {'clay'}, 'Sergiy_Stakhovsky': {'hard'}, 'Shintaro_Mochizuki': {'clay'},
                        'Sho_Shimabukuro': {'grass'},
                        'Soon_Woo_Kwon': {'hard'}, 'Stan_Wawrinka': {'grass', 'hard', 'clay'},
                        'Stefan_Kozlov': {'hard'},
                        'Stefanos_Tsitsipas': {'grass', 'hard', 'clay'}, 'Steve_Darcis': {'hard'},
                        'Steve_Johnson': {'grass', 'hard', 'clay'},
                        'Steven_Diez': {'hard'}, 'Strong_Kirchheimer': {'hard'}, 'Sumit_Nagal': {'clay'},
                        'Tallon_Griekspoor': {'grass', 'hard', 'clay'}, 'Taro_Daniel': {'hard', 'clay'},
                        'Taylor_Fritz': {'grass', 'hard', 'clay'}, 'Tennys_Sandgren': {'hard'},
                        'Thanasi_Kokkinakis': {'hard', 'clay'},
                        'Thiago_Agustin_Tirante': {'clay'}, 'Thiago_Monteiro': {'hard', 'clay'},
                        'Thiago_Seyboth_Wild': {'grass', 'hard', 'clay'}, 'Thijs_Boogaard': {'hard'},
                        'Thomaz_Bellucci': {'clay'},
                        'Tim_Van_Rijthoven': {'grass', 'hard', 'clay'}, 'Timofey_Skatov': {'hard', 'clay'},
                        'Titouan_Droguet': {'clay'},
                        'Tomas_Barrios_Vera': {'hard', 'clay'}, 'Tomas_Machac': {'grass', 'hard', 'clay'},
                        'Tomas_Martin_Etcheverry': {'hard', 'clay'}, 'Tomasz_Berkieta': {'clay'},
                        'Tommy_Paul': {'grass', 'hard', 'clay'},
                        'Tommy_Robredo': {'clay'}, 'Tristan_Schoolkate': {'hard'}, 'Tung_Lin_Wu': {'hard'},
                        'Ugo_Blanchet': {'hard'},
                        'Ugo_Humbert': {'grass', 'hard', 'clay'}, 'Valentin_Vacherot': {'clay'},
                        'Vasek_Pospisil': {'hard'},
                        'Viktor_Durasovic': {'hard'}, 'Viktor_Troicki': {'clay'}, 'Vilius_Gaubas': {'clay'},
                        'Vit_Kopriva': {'grass'},
                        'Yannick_Hanfmann': {'grass', 'hard', 'clay'}, 'Yasutaka_Uchiyama': {'hard'},
                        'Yibing_Wu': {'grass', 'hard', 'clay'},
                        'Yoshihito_Nishioka': {'grass', 'hard', 'clay'}, 'Yosuke_Watanuki': {'grass', 'hard'},
                        'Younes_Lalami_Laaroussi': {'clay'}, 'Yu_Hsiou_Hsu': {'hard'}, 'Yuichi_Sugita': {'hard'},
                        'Zachary_Svajda': {'hard'},
                        'Zdenek_Kolar': {'clay'}, 'Zhizhen_Zhang': {'grass', 'hard', 'clay'}, 'Zizou_Bergs': {'hard'},
                        'Zsombor_Piros': {'clay'}}
